name: Deploy to staging

on:
  pull_request:
    types:
      - labeled

jobs:
  Build-Docker-Image:
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t myapp
